"""Provide Firebird 4.0+ specific information.

    Variables:
        MAX_IDENTIFIER_LENGTH -> int
        RESERVED_WORDS -> set
        ISCHEMA_NAMES -> dict

.._Firebird 4.0:
    https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html

.._Firebird 5.0:
    https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref50/firebird-50-language-reference.html

"""

import sqlalchemy.types as sa_types

# https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html
# For Firebird version 4.0 and greater, the "...maximum identifier length is 63 characters
# character set UTF8 (252 bytes)".
MAX_IDENTIFIER_LENGTH = 63

# https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-reskeywords-reswords
# This set is also good for Firebird version 5.0 Beta 1
# Note that reserved words in Firebird 5 are the same as those in Firebird 4
RESERVED_WORDS = {
    "add",
    "admin",
    "all",
    "alter",
    "and",
    "any",
    "as",
    "at",
    "avg",
    "begin",
    "between",
    "bigint",
    "binary",
    "bit_length",
    "blob",
    "boolean",
    "both",
    "by",
    "case",
    "cast",
    "char",
    "character",
    "character_length",
    "char_length",
    "check",
    "close",
    "collate",
    "column",
    "comment",
    "commit",
    "connect",
    "constraint",
    "corr",
    "count",
    "covar_pop",
    "covar_samp",
    "create",
    "cross",
    "current",
    "current_connection",
    "current_date",
    "current_role",
    "current_time",
    "current_timestamp",
    "current_transaction",
    "current_user",
    "cursor",
    "date",
    "day",
    "dec",
    "decfloat",
    "decimal",
    "declare",
    "default",
    "delete",
    "deleting",
    "deterministic",
    "disconnect",
    "distinct",
    "double",
    "drop",
    "else",
    "end",
    "escape",
    "execute",
    "exists",
    "external",
    "extract",
    "false",
    "fetch",
    "filter",
    "float",
    "for",
    "foreign",
    "from",
    "full",
    "function",
    "gdscode",
    "global",
    "grant",
    "group",
    "having",
    "hour",
    "in",
    "index",
    "inner",
    "insensitive",
    "insert",
    "inserting",
    "int",
    "int128",
    "integer",
    "into",
    "is",
    "join",
    "lateral",
    "leading",
    "left",
    "like",
    "local",
    "localtime",
    "localtimestamp",
    "long",
    "lower",
    "max",
    "merge",
    "min",
    "minute",
    "month",
    "national",
    "natural",
    "nchar",
    "no",
    "not",
    "null",
    "numeric",
    "octet_length",
    "of",
    "offset",
    "on",
    "only",
    "open",
    "or",
    "order",
    "outer",
    "over",
    "parameter",
    "plan",
    "position",
    "post_event",
    "precision",
    "primary",
    "procedure",
    "publication",
    "rdb$db_key",
    "rdb$error",
    "rdb$get_context",
    "rdb$get_transaction_cn",
    "rdb$record_version",
    "rdb$role_in_use",
    "rdb$set_context",
    "rdb$system_privilege",
    "real",
    "record_version",
    "recreate",
    "recursive",
    "references",
    "regr_avgx",
    "regr_avgy",
    "regr_count",
    "regr_intercept",
    "regr_r2",
    "regr_slope",
    "regr_sxx",
    "regr_sxy",
    "regr_syy",
    "release",
    "resetting",
    "return",
    "returning_values",
    "returns",
    "revoke",
    "right",
    "rollback",
    "row",
    "rows",
    "row_count",
    "savepoint",
    "scroll",
    "second",
    "select",
    "sensitive",
    "set",
    "similar",
    "smallint",
    "some",
    "sqlcode",
    "sqlstate",
    "start",
    "stddev_pop",
    "stddev_samp",
    "sum",
    "table",
    "then",
    "time",
    "timestamp",
    "timezone_hour",
    "timezone_minute",
    "to",
    "trailing",
    "trigger",
    "trim",
    "true",
    "unbounded",
    "union",
    "unique",
    "unknown",
    "update",
    "updating",
    "upper",
    "user",
    "using",
    "value",
    "values",
    "varbinary",
    "varchar",
    "variable",
    "varying",
    "var_pop",
    "var_samp",
    "view",
    "when",
    "where",
    "while",
    "window",
    "with",
    "without",
    "year",
}

# https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref50/firebird-50-language-reference.html#fblangref50-datatypes-syntax-scalar
# https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-datatypes-syntax-scalar
ISCHEMA_NAMES = {
    "SMALLINT": sa_types.SMALLINT,
    "INT": sa_types.INTEGER,
    "INTEGER": sa_types.INTEGER,
    "BIGINT": sa_types.BIGINT,
    "INT128": sa_types.BIGINT,  # TODO: INT128
    "REAL": sa_types.REAL,
    "FLOAT": sa_types.FLOAT,
    "DOUBLE PRECISION": sa_types.FLOAT,
    "DECFLOAT": sa_types.FLOAT,  # TODO: DECFLOAT
    "BOOLEAN": sa_types.BOOLEAN,
    "DATE": sa_types.DATE,
    "TIME": sa_types.TIME,
    "TIME WITH TIME ZONE": sa_types.TIME,
    "TIME WITHOUT TIME ZONE": sa_types.TIME,
    "TIMESTAMP": sa_types.TIMESTAMP,
    "TIMESTAMP WITH TIME ZONE": sa_types.TIMESTAMP,
    "TIMESTAMP WITHOUT TIME ZONE": sa_types.TIMESTAMP,
    "DECIMAL": sa_types.NUMERIC,
    "NUMERIC": sa_types.NUMERIC,
    "VARCHAR": sa_types.VARCHAR,
    "CHAR VARYING": sa_types.VARCHAR,
    "CHARACTER VARYING": sa_types.VARCHAR,
    "CHAR": sa_types.CHAR,
    "CHARACTER": sa_types.CHAR,
    "BINARY": sa_types.BINARY,
    "VARBINARY": sa_types.VARBINARY,
    "BINARY VARYING": sa_types.VARBINARY,
    # Compatibility
    "SHORT": sa_types.SMALLINT,
    "LONG": sa_types.INTEGER,
    "QUAD": sa_types.FLOAT,
    "TEXT": sa_types.TEXT,
    "INT64": sa_types.BIGINT,
    "LONG FLOAT": sa_types.FLOAT,
    "DOUBLE": sa_types.FLOAT,
    "VARYING": sa_types.VARCHAR,
    "CSTRING": sa_types.CHAR,
    "BLOB": sa_types.BLOB,
    "NCHAR VARYING": sa_types.VARCHAR,
    "NATIONAL CHAR VARYING": sa_types.VARCHAR,
    "NATIONAL CHARACTER VARYING": sa_types.VARCHAR,
    "NCHAR": sa_types.CHAR,
    "NATIONAL CHAR": sa_types.CHAR,
    "NATIONAL CHARACTER": sa_types.CHAR,
}
