"""Provide Firebird 2.5 specific information.

    Variables:
        MAX_IDENTIFIER_LENGTH -> int
        RESERVED_WORDS -> set
        ISCHEMA_NAMES -> dict

.._Firebird 2.5:
    https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref25/firebird-25-language-reference.html#fblangref25-intro

"""

import sqlalchemy.types as sa_types

# https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref25/firebird-25-language-reference.html#fblangref25-datatypes
# "Length cannot exceed 31 characters."
MAX_IDENTIFIER_LENGTH = 31

# https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref25/firebird-25-language-reference.html#fblangref25-appx03-reskeywords
# This set is for Firebird versions >= 2.5.1
RESERVED_WORDS = {
    "add",
    "admin",
    "all",
    "alter",
    "and",
    "any",
    "as",
    "at",
    "avg",
    "begin",
    "between",
    "bigint",
    "bit_length",
    "blob",
    "both",
    "by",
    "case",
    "cast",
    "char",
    "char_length",
    "character",
    "character_length",
    "check",
    "close",
    "collate",
    "column",
    "commit",
    "connect",
    "constraint",
    "count",
    "create",
    "cross",
    "current",
    "current_connection",
    "current_date",
    "current_role",
    "current_time",
    "current_timestamp",
    "current_transaction",
    "current_user",
    "cursor",
    "date",
    "day",
    "dec",
    "decimal",
    "declare",
    "default",
    "delete",
    "deleting",
    "disconnect",
    "distinct",
    "double",
    "drop",
    "else",
    "end",
    "escape",
    "execute",
    "exists",
    "external",
    "extract",
    "fetch",
    "filter",
    "float",
    "for",
    "foreign",
    "from",
    "full",
    "function",
    "gdscode",
    "global",
    "grant",
    "group",
    "having",
    "hour",
    "in",
    "index",
    "inner",
    "insensitive",
    "insert",
    "inserting",
    "int",
    "integer",
    "into",
    "is",
    "join",
    "leading",
    "left",
    "like",
    "long",
    "lower",
    "max",
    "maximum_segment",
    "merge",
    "min",
    "minute",
    "month",
    "national",
    "natural",
    "nchar",
    "no",
    "not",
    "null",
    "numeric",
    "octet_length",
    "of",
    "on",
    "only",
    "open",
    "or",
    "order",
    "outer",
    "parameter",
    "plan",
    "position",
    "post_event",
    "precision",
    "primary",
    "procedure",
    "rdb$db_key",
    "real",
    "record_version",
    "recreate",
    "recursive",
    "references",
    "release",
    "returning_values",
    "returns",
    "revoke",
    "right",
    "rollback",
    "row_count",
    "rows",
    "savepoint",
    "second",
    "select",
    "sensitive",
    "set",
    "similar",
    "smallint",
    "some",
    "sqlcode",
    "sqlstate",
    "start",
    "sum",
    "table",
    "then",
    "time",
    "timestamp",
    "to",
    "trailing",
    "trigger",
    "trim",
    "union",
    "unique",
    "update",
    "updating",
    "upper",
    "user",
    "using",
    "value",
    "values",
    "varchar",
    "variable",
    "varying",
    "view",
    "when",
    "where",
    "while",
    "with",
    "year",
}

# https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref25/firebird-25-language-reference.html#fblangref25-datatypes
ISCHEMA_NAMES = {
    "SMALLINT": sa_types.SMALLINT,
    "INT": sa_types.INTEGER,
    "INTEGER": sa_types.INTEGER,
    "BIGINT": sa_types.BIGINT,
    "REAL": sa_types.REAL,
    "FLOAT": sa_types.FLOAT,
    "DOUBLE PRECISION": sa_types.FLOAT,
    "DATE": sa_types.DATE,
    "TIME": sa_types.TIME,
    "TIMESTAMP": sa_types.TIMESTAMP,
    "DECIMAL": sa_types.NUMERIC,
    "NUMERIC": sa_types.NUMERIC,
    "VARCHAR": sa_types.VARCHAR,
    "CHAR VARYING": sa_types.VARCHAR,
    "CHARACTER VARYING": sa_types.VARCHAR,
    "CHAR": sa_types.CHAR,
    "CHARACTER": sa_types.CHAR,
    # Compatibility
    "SHORT": sa_types.SMALLINT,
    "LONG": sa_types.INTEGER,
    "QUAD": sa_types.FLOAT,
    "TEXT": sa_types.TEXT,
    "INT64": sa_types.BIGINT,
    "LONG FLOAT": sa_types.FLOAT,
    "DOUBLE": sa_types.FLOAT,
    "VARYING": sa_types.VARCHAR,
    "CSTRING": sa_types.CHAR,
    "BLOB": sa_types.BLOB,
    "NCHAR VARYING": sa_types.VARCHAR,
    "NATIONAL CHAR VARYING": sa_types.VARCHAR,
    "NATIONAL CHARACTER VARYING": sa_types.VARCHAR,
    "NCHAR": sa_types.CHAR,
    "NATIONAL CHAR": sa_types.CHAR,
    "NATIONAL CHARACTER": sa_types.CHAR,
}
